# If you come from bash you might have to change your $PATH.
export PATH=/snap/bin:$HOME/.local/bin:$HOME/bin:/usr/local/bin:/usr/bin:$PATH

# Path to zsh folder.
export ZSH=$HOME/linuxsettings/zshrc

# Path to zplug folder.
export ZPLUG_HOME=$HOME/.zplug

# Nvim as standard editor
export EDITOR=nvim

autoload -Uz compinit

# Source all config files
for config_file ($ZSH/lib/*.zsh); do
  source $config_file
done

source $ZSH/zshtheme.zsh-theme

# Locale
export LC_ALL=C

# Zplug plugin management
source ~/.zplug/init.zsh
zplug "skywind3000/z.lua"
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-syntax-highlighting"
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern)
typeset -A ZSH_HIGHLIGHT_PATTERNS
ZSH_HIGHLIGHT_PATTERNS+=("rm -rf *" "fg=white,bold,bg=none")
ZSH_HIGHLIGHT_PATTERNS+=("git rm *" "fg=white,bold,bg=none")
typeset -gA ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[path]="fg=none"
ZSH_HIGHLIGHT_STYLES[alias]="fg=magenta,bold"
ZSH_HIGHLIGHT_STYLES[command]="fg=magenta,bold"
ZSH_HIGHLIGHT_STYLES[fuction]="fg=blue,bold"

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load
eval "$(lua ~/.zplug/repos/skywind3000/z.lua/z.lua --init zsh)"

bindkey -v
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
