#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to bash folder.
export BASH=$HOME/linuxsettings/bashrc

# Source all config files
for config_file in $BASH/lib/*.sh; do
  source $config_file
done

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
