# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to zsh folder.
export ZSH=$HOME/linuxsettings/zsh

for config_file ($ZSH/lib/*.zsh); do
  source $config_file
done

source $ZSH/zshtheme.zsh-theme

