#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return
if [[ -f ~/.bash_aliases ]]; then
  . ~/.bash_aliases
fi

if [[ -f ~/.bash_export ]]; then
  . ~/.bash_export
fi

if [[ -f ~/.bash_settings ]]; then
  . ~/.bash_settings
fi

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
